=head1 NAME

Firefox Updater - fetch and install firefox nightly builds

=head2 DESCRIPTION

Firefox Updater is a perl script which fetches Firefox trunk nightly builds and
installs them.

This script checks the currently installed version against the latest one
hosted at ftp.mozilla.org. If a new version is found, and firefox isn't
currently running, then the new version is downloaded, unpacked and installed.
This completely replaces the old version's files, but settings, history, and
bookmarks are safe, as they're stored outside the application directory.

=head2 SYNOPSIS

    # Check for a new daily build and install if one is found.
    firefox_updater.pl

=head2 VERSION

version 1.00 - 2011-02-01

    Now works from end to end.

=head2 TODO

=over 4

=item * Install the new version.

=back

=head2 HISTORY

version 0.01 - 2011-01-27

    Now hosted on github - http://github.com/d5ve/firefox-updater

=head2 AUTHOR

Dave Webb <firefox-updater@d5ve.com>

=head2 CREDITS

Firefox Updater was inspired by a script for updating the chrome browser, found 
at http://www.macosxhints.com/article.php?story=20090604081030791 and written by 
user oblahdioblidaa.

=head2 LICENCE

Firefox Updater is free software. It comes without any warranty, to the extent permitted
by applicable law. 

Firefox Updater is released under the I<WTFPL Version 2.0> licence - L<http://sam.zoy.org/wtfpl/COPYING>

=cut

